import type { MuscleId } from "@/store/marcola";

/**
 * Marcola Prime — Biblioteca de Exercícios v2.
 *
 * Visual data-first: nenhuma imagem. Cada exercício carrega:
 * - equipamento (com nome de máquina específico quando aplicável)
 * - músculo primário + secundários
 * - dificuldade (1-3)
 * - tempo, descanso e tempo padrão
 * - shortDescription (1-2 linhas) e instruções detalhadas
 * - rating estilo "Gym Tok" (curado por consenso de criadores fitness, refresh via Perplexity)
 * - tags (composto/isolador/unilateral/explosivo)
 */

export type Equipment =
  | "barbell"
  | "dumbbell"
  | "machine"
  | "cable"
  | "bodyweight"
  | "kettlebell"
  | "smith"
  | "cardio";

export type ExerciseTag =
  | "compound"
  | "isolation"
  | "unilateral"
  | "explosive"
  | "core"
  | "stretch"
  | "beginner-friendly"
  | "advanced";

export interface ExerciseRating {
  /** 0.0 - 5.0 */
  stars: number;
  /** Quantidade estimada de menções/avaliações consideradas na curadoria. */
  sampleSize: number;
  source: "curated" | "deep-research";
  /** ISO timestamp. */
  updatedAt: string;
  /** Resumo curto do "porquê" da nota (cita consenso, eficácia, popularidade). */
  rationale: string;
}

export interface LibraryExercise {
  id: string;
  name: string;
  equipment: Equipment;
  /** Nome específico da máquina/implemento (e.g. "Leg Press 45°", "Smith", "Hack Squat"). */
  machineName?: string;
  primary: MuscleId;
  secondary: MuscleId[];
  difficulty: 1 | 2 | 3;
  defaultRestSeconds: number;
  defaultTempo: string;
  /** 1-2 linhas exibido no card e topo do sheet. */
  shortDescription: string;
  instructions: string[];
  /** Dicas técnicas curtas (cues). */
  cues: string[];
  rating: ExerciseRating;
  tags: ExerciseTag[];
}

const CURATED_AT = "2026-06-30T00:00:00Z";

const rate = (stars: number, sampleSize: number, rationale: string): ExerciseRating => ({
  stars, sampleSize, source: "curated", updatedAt: CURATED_AT, rationale,
});

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  /* ════════════════ PESO LIVRE — BARRA ════════════════ */
  {
    id: "lib-supino-reto", name: "Supino Reto Barra", equipment: "barbell",
    primary: "chest", secondary: ["shoulders", "triceps"], difficulty: 3,
    defaultRestSeconds: 150, defaultTempo: "3-1-1-0",
    shortDescription: "Padrão-ouro de força e massa para peito. Composto multiarticular pesado.",
    instructions: [
      "Deite no banco, escápulas retraídas e deprimidas, pés firmes no chão.",
      "Pegada um pouco mais larga que os ombros, polegares envolvendo a barra.",
      "Desça controlando até tocar levemente a linha do mamilo.",
      "Empurre explosivamente sem perder o arco lombar moderado.",
    ],
    cues: ["Aperte a barra como se fosse entortá-la", "Pés cravados", "Cotovelos ~70°"],
    rating: rate(4.8, 1280, "Consenso quase unânime entre Jeff Nippard, Mike Israetel e Chris Bumstead como base do peitoral. Viraliza no Gym Tok pela métrica de força."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-supino-inclinado-barra", name: "Supino Inclinado Barra", equipment: "barbell",
    primary: "chest", secondary: ["shoulders", "triceps"], difficulty: 3,
    defaultRestSeconds: 120, defaultTempo: "3-1-1-0",
    shortDescription: "Foco na porção clavicular do peitoral. Banco 30-45°.",
    instructions: [
      "Banco entre 30-45°. Pega ligeiramente mais larga que ombros.",
      "Desça para a parte alta do peito (linha das clavículas).",
      "Empurre sem deixar os cotovelos abrirem 90°.",
    ],
    cues: ["Não passe de 45° (vira ombro)", "Escápula travada"],
    rating: rate(4.7, 980, "Tendência forte no Gym Tok pós-Nippard: superior do peito é o ponto fraco mais comum, e este é o melhor estímulo."),
    tags: ["compound"],
  },
  {
    id: "lib-supino-declinado-barra", name: "Supino Declinado Barra", equipment: "barbell",
    primary: "chest", secondary: ["triceps"], difficulty: 2,
    defaultRestSeconds: 120, defaultTempo: "3-1-1-0",
    shortDescription: "Enfatiza porção inferior do peitoral. Menos demanda de ombro.",
    instructions: [
      "Banco em declínio 15-30°, prenda os pés.",
      "Pegada um pouco mais larga que ombros.",
      "Desça à linha do peito baixo, empurre em arco curto.",
    ],
    cues: ["Não desça até pescoço", "Quadril estável"],
    rating: rate(3.6, 410, "Menos popular: peito inferior é desenvolvido por supino reto na maioria. Útil em rotação."),
    tags: ["compound"],
  },
  {
    id: "lib-agachamento-livre", name: "Agachamento Livre", equipment: "barbell",
    primary: "quads", secondary: ["glutes", "core", "lower-back", "hamstrings"], difficulty: 3,
    defaultRestSeconds: 180, defaultTempo: "3-1-1-0",
    shortDescription: "Rei dos exercícios de perna. Estímulo total de membros inferiores e core.",
    instructions: [
      "Barra no trapézio (high ou low bar), pés na largura dos ombros.",
      "Inicie empurrando o quadril para trás, joelhos seguem os pés.",
      "Desça até pelo menos a paralela, mantendo peito alto.",
      "Suba empurrando o chão de forma simétrica.",
    ],
    cues: ["Joelhos alinhados aos pés", "Não jogue tronco à frente", "Respire no topo"],
    rating: rate(4.9, 1640, "Praticamente unanimidade: melhor custo-benefício de força e massa de perna. Domina o Gym Tok com PR videos."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-front-squat", name: "Front Squat", equipment: "barbell",
    primary: "quads", secondary: ["core", "glutes"], difficulty: 3,
    defaultRestSeconds: 150, defaultTempo: "3-1-1-0",
    shortDescription: "Variação anterior que demanda mais quadríceps e core que o agachamento tradicional.",
    instructions: [
      "Barra apoiada nos deltóides anteriores, cotovelos altos.",
      "Desça mantendo tronco perpendicular, joelhos para frente.",
      "Suba sem inclinar o tronco — barra cai se inclinar.",
    ],
    cues: ["Cotovelos sempre altos", "Pega frontal ou cross-arm"],
    rating: rate(4.4, 720, "Cresce no Gym Tok pelo apelo estético no quadríceps. Demanda mobilidade de punho/torácica."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-deadlift-convencional", name: "Levantamento Terra Convencional", equipment: "barbell",
    primary: "hamstrings", secondary: ["glutes", "lower-back", "traps", "lats", "forearms"], difficulty: 3,
    defaultRestSeconds: 180, defaultTempo: "2-0-2-0",
    shortDescription: "Composto pesado total. Cadeia posterior + força de pegada.",
    instructions: [
      "Pés na largura do quadril, barra sobre o meio do pé.",
      "Quadril alto, ombros à frente da barra, lats engatados.",
      "Empurre o chão e estenda quadril/joelhos juntos.",
      "Desça controlando — não solte do topo.",
    ],
    cues: ["Tire a folga da barra antes de puxar", "Lombar neutra sempre"],
    rating: rate(4.8, 1490, "Consenso: melhor exercício para cadeia posterior global. Métrica de força do Gym Tok."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-deadlift-sumo", name: "Terra Sumô", equipment: "barbell",
    primary: "glutes", secondary: ["quads", "hamstrings", "lower-back"], difficulty: 3,
    defaultRestSeconds: 180, defaultTempo: "2-0-2-0",
    shortDescription: "Pegada interna, pés abertos. Reduz cisalhamento lombar; ativa adutor e glúteo.",
    instructions: [
      "Pés bem abertos, pontas viradas para fora ~45°.",
      "Pegada interna, braços verticais.",
      "Empurre o chão sentindo glúteo e quadríceps.",
    ],
    cues: ["Joelhos para fora", "Peito alto na largada"],
    rating: rate(4.5, 860, "Forte no Gym Tok feminino para glúteos. Melhor que convencional para quem tem braço curto."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-stiff", name: "Stiff Barra", equipment: "barbell",
    primary: "hamstrings", secondary: ["glutes", "lower-back"], difficulty: 2,
    defaultRestSeconds: 120, defaultTempo: "3-1-1-0",
    shortDescription: "Hinge puro para posteriores e glúteo. Joelhos quase travados.",
    instructions: [
      "Joelhos com leve flexão fixa, quadril vai para trás.",
      "Barra desliza próxima às pernas.",
      "Desça até sentir alongamento; suba contraindo glúteo.",
    ],
    cues: ["Quadril atrás, não desce em squat", "Lombar neutra"],
    rating: rate(4.7, 1020, "Top 3 para posterior de coxa segundo Nippard. Bombado no Gym Tok pelo 'mind-muscle'."),
    tags: ["compound"],
  },
  {
    id: "lib-romanian-deadlift", name: "Romanian Deadlift (RDL)", equipment: "barbell",
    primary: "hamstrings", secondary: ["glutes", "lower-back"], difficulty: 2,
    defaultRestSeconds: 120, defaultTempo: "3-1-1-0",
    shortDescription: "Hinge com joelho ligeiramente mais flexível que stiff. Maior alongamento.",
    instructions: [
      "Comece em pé com a barra (não do chão).",
      "Quadril para trás, joelhos seguem leve flexão.",
      "Desça até meio da canela ou alongamento máximo.",
    ],
    cues: ["Peso no calcanhar", "Barra colada nas pernas"],
    rating: rate(4.7, 980, "Variação favorita de coaches modernos. Stretch enfatizado = mais hipertrofia."),
    tags: ["compound"],
  },
  {
    id: "lib-remada-curvada", name: "Remada Curvada Barra", equipment: "barbell",
    primary: "lats", secondary: ["traps", "biceps", "lower-back"], difficulty: 3,
    defaultRestSeconds: 120, defaultTempo: "2-1-2-0",
    shortDescription: "Composto horizontal para densidade de costas.",
    instructions: [
      "Tronco ~45°, joelhos levemente flexionados.",
      "Pegada pronada ou supinada largura dos ombros.",
      "Puxe ao baixo do abdômen, contraia escápulas.",
    ],
    cues: ["Não use tronco para impulsionar", "Cotovelo próximo ao corpo"],
    rating: rate(4.6, 870, "Clássico. Pendlay variation viraliza no Gym Tok para força explosiva."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-desenvolvimento-militar", name: "Desenvolvimento Militar", equipment: "barbell",
    primary: "shoulders", secondary: ["triceps", "core"], difficulty: 3,
    defaultRestSeconds: 120, defaultTempo: "2-1-1-0",
    shortDescription: "Composto vertical para ombro. De pé, sem assistência do banco.",
    instructions: [
      "Em pé, pés na largura dos ombros, core e glúteo travados.",
      "Barra na linha das clavículas, cotovelos um pouco à frente.",
      "Empurre acima da cabeça, leve cabeça para frente no topo.",
    ],
    cues: ["Não arqueie lombar excessivamente", "Glúteo apertado"],
    rating: rate(4.5, 760, "Padrão de força. Mike Israetel cita como composto para ombro nº1."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-push-press", name: "Push Press", equipment: "barbell",
    primary: "shoulders", secondary: ["triceps", "quads", "core"], difficulty: 3,
    defaultRestSeconds: 150, defaultTempo: "2-0-1-0",
    shortDescription: "Desenvolvimento com leve dip de pernas. Permite carga maior.",
    instructions: [
      "Barra nas clavículas. Pequena flexão de joelhos.",
      "Extenda explosivamente e empurre a barra para cima.",
      "Desça controlado.",
    ],
    cues: ["Dip curto e vertical", "Não use squat"],
    rating: rate(4.2, 410, "Popular entre atletas. Útil para quebrar platô de força no ombro."),
    tags: ["compound", "explosive", "advanced"],
  },
  {
    id: "lib-rosca-direta-barra", name: "Rosca Direta Barra", equipment: "barbell",
    primary: "biceps", secondary: ["forearms"], difficulty: 1,
    defaultRestSeconds: 75, defaultTempo: "2-1-2-0",
    shortDescription: "Isolador clássico para bíceps. Pega supinada.",
    instructions: [
      "Em pé, cotovelos colados ao tronco.",
      "Pegada supinada na largura dos ombros.",
      "Curl até o pico, sem movimentar cotovelo.",
    ],
    cues: ["Cotovelo fixo", "Sem balanço de tronco"],
    rating: rate(4.4, 1120, "Clássico universal. Barra W reduz tensão no punho — variante mais popular."),
    tags: ["isolation", "beginner-friendly"],
  },
  {
    id: "lib-rosca-w", name: "Rosca Direta Barra W", equipment: "barbell",
    primary: "biceps", secondary: ["forearms"], difficulty: 1,
    defaultRestSeconds: 75, defaultTempo: "2-1-2-0",
    shortDescription: "Mesma execução da rosca direta, barra W reduz estresse no punho.",
    instructions: [
      "Pegada nas curvaturas internas da barra W.",
      "Cotovelos colados, curl controlado.",
    ],
    cues: ["Punho neutro", "Sem balançar"],
    rating: rate(4.3, 690, "Alternativa segura à barra reta. Recomendado para quem sente desconforto no punho."),
    tags: ["isolation", "beginner-friendly"],
  },
  {
    id: "lib-triceps-testa", name: "Tríceps Testa Barra W", equipment: "barbell",
    primary: "triceps", secondary: [], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "3-1-1-0",
    shortDescription: "Extensão deitado. Alonga cabeça longa do tríceps.",
    instructions: [
      "Deitado no banco, barra W com pega fechada.",
      "Cotovelos apontados ao teto, fixos.",
      "Desça atrás/acima da testa, estenda.",
    ],
    cues: ["Cotovelos não abrem", "Controle na descida"],
    rating: rate(4.4, 540, "Top para tríceps por permitir carga e stretch. Pode estressar cotovelo se sobrecarregar."),
    tags: ["isolation"],
  },
  {
    id: "lib-good-morning", name: "Good Morning", equipment: "barbell",
    primary: "hamstrings", secondary: ["lower-back", "glutes"], difficulty: 2,
    defaultRestSeconds: 90, defaultTempo: "3-1-1-0",
    shortDescription: "Hinge com barra no trapézio. Foco lombar/posterior.",
    instructions: [
      "Barra apoiada no trapézio como agachamento.",
      "Quadril vai para trás, tronco inclina à frente.",
      "Volte estendendo quadril.",
    ],
    cues: ["Não force lombar", "Use carga leve"],
    rating: rate(3.8, 320, "Útil como acessório. Não usar com cargas altas — risco lombar."),
    tags: ["compound"],
  },
  {
    id: "lib-encolhimento-barra", name: "Encolhimento Barra", equipment: "barbell",
    primary: "traps", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "1-1-1-1",
    shortDescription: "Isolador para trapézio superior.",
    instructions: [
      "Barra à frente do corpo, pegada pronada.",
      "Eleve ombros verticalmente, sem rotacionar.",
      "Segure 1s no topo.",
    ],
    cues: ["Sem rolar ombro", "Não use bíceps"],
    rating: rate(4.0, 450, "Eficaz para trapézio superior. Halteres dão mais ROM."),
    tags: ["isolation"],
  },
  {
    id: "lib-clean-power", name: "Power Clean", equipment: "barbell",
    primary: "glutes", secondary: ["hamstrings", "traps", "quads", "shoulders"], difficulty: 3,
    defaultRestSeconds: 180, defaultTempo: "explosivo",
    shortDescription: "Levantamento olímpico explosivo. Potência total.",
    instructions: [
      "Posição de terra, puxe explosivamente.",
      "Triple extension (tornozelo/joelho/quadril).",
      "Pegue a barra no rack frontal.",
    ],
    cues: ["Movimento contínuo", "Sem pausa"],
    rating: rate(4.3, 380, "Excelente para potência. Requer técnica — não para hipertrofia pura."),
    tags: ["compound", "explosive", "advanced"],
  },
  {
    id: "lib-zercher-squat", name: "Zercher Squat", equipment: "barbell",
    primary: "quads", secondary: ["core", "glutes", "biceps"], difficulty: 3,
    defaultRestSeconds: 150, defaultTempo: "3-1-1-0",
    shortDescription: "Barra na dobra do cotovelo. Brutal para core e antebraço.",
    instructions: [
      "Barra apoiada nos antebraços/cotovelos.",
      "Agache mantendo tronco ereto.",
    ],
    cues: ["Use proteção/manta", "Coluna neutra"],
    rating: rate(3.7, 220, "Nicho. Bom para variar e fortalecer agarre/core."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-supino-pegada-fechada", name: "Supino Pegada Fechada", equipment: "barbell",
    primary: "triceps", secondary: ["chest", "shoulders"], difficulty: 2,
    defaultRestSeconds: 120, defaultTempo: "3-1-1-0",
    shortDescription: "Supino com pega na largura dos ombros. Foco em tríceps.",
    instructions: [
      "Pegada na largura dos ombros (não menor).",
      "Cotovelos próximos ao tronco.",
      "Desça à parte baixa do peito.",
    ],
    cues: ["Pega muito fechada estressa punho", "Cotovelos colados"],
    rating: rate(4.5, 740, "Top para tríceps com carga pesada. Excelente combo com isoladores."),
    tags: ["compound"],
  },

  /* ════════════════ PESO LIVRE — HALTER ════════════════ */
  {
    id: "lib-supino-halter", name: "Supino Reto Halter", equipment: "dumbbell",
    primary: "chest", secondary: ["shoulders", "triceps"], difficulty: 2,
    defaultRestSeconds: 120, defaultTempo: "3-1-1-0",
    shortDescription: "Maior ROM e ativação que barra. Mais simétrico.",
    instructions: [
      "Halteres na altura do peito, cotovelos ~70°.",
      "Empurre em arco até quase tocarem no topo.",
      "Desça até alongamento total.",
    ],
    cues: ["Não trave cotovelo", "Punho neutro/pronado"],
    rating: rate(4.7, 1180, "Favorito Gym Tok para hipertrofia. ROM maior que barra."),
    tags: ["compound"],
  },
  {
    id: "lib-supino-inclinado-halter", name: "Supino Inclinado Halter", equipment: "dumbbell",
    primary: "chest", secondary: ["shoulders"], difficulty: 2,
    defaultRestSeconds: 120, defaultTempo: "3-1-1-0",
    shortDescription: "Banco 30-45° para superior do peito com halteres.",
    instructions: [
      "Banco entre 30-45°, halteres na altura do peito.",
      "Pressione em arco, contraindo peito superior.",
    ],
    cues: ["Não passe de 45°", "Escápula retraída"],
    rating: rate(4.8, 1340, "Provavelmente o exercício de peito superior mais recomendado no Gym Tok atual."),
    tags: ["compound"],
  },
  {
    id: "lib-crucifixo-halter", name: "Crucifixo Halter", equipment: "dumbbell",
    primary: "chest", secondary: ["shoulders"], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "3-1-2-0",
    shortDescription: "Isolador de peitoral com stretch máximo.",
    instructions: [
      "Halteres acima do peito, palmas voltadas.",
      "Abra em arco com cotovelos levemente flexionados.",
      "Sinta o stretch e volte contraindo.",
    ],
    cues: ["Cotovelos fixos", "Sem 'pressionar' no topo"],
    rating: rate(4.3, 580, "Bom para variar. Stretch é o ponto forte."),
    tags: ["isolation", "stretch"],
  },
  {
    id: "lib-crucifixo-inclinado", name: "Crucifixo Inclinado", equipment: "dumbbell",
    primary: "chest", secondary: [], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "3-1-2-0",
    shortDescription: "Stretch para peito superior. Banco 30°.",
    instructions: ["Banco a 30°, halteres acima do peito.", "Abra controlado até alongamento."],
    cues: ["Não desça abaixo do peito", "Stretch sem dor"],
    rating: rate(4.4, 510, "Variação preferida para peito superior em hipertrofia moderna."),
    tags: ["isolation", "stretch"],
  },
  {
    id: "lib-pullover-halter", name: "Pullover Halter", equipment: "dumbbell",
    primary: "lats", secondary: ["chest", "triceps"], difficulty: 2,
    defaultRestSeconds: 90, defaultTempo: "3-1-2-0",
    shortDescription: "Stretch lat / costelas. Foco depende da execução.",
    instructions: [
      "Deitado transversal no banco, halter acima do peito.",
      "Desça atrás da cabeça com leve flexão de cotovelo.",
      "Volte contraindo lats.",
    ],
    cues: ["Costelas para baixo", "Sem hiperextender lombar"],
    rating: rate(4.0, 420, "Clássico antigo, voltou ao Gym Tok para 'expansão torácica'. Bom acessório."),
    tags: ["compound", "stretch"],
  },
  {
    id: "lib-desenvolvimento-halter", name: "Desenvolvimento Halter", equipment: "dumbbell",
    primary: "shoulders", secondary: ["triceps"], difficulty: 2,
    defaultRestSeconds: 90, defaultTempo: "2-1-1-0",
    shortDescription: "Maior ROM que barra. Sentado ou em pé.",
    instructions: [
      "Sentado com banco a 80-90°, halteres na altura das orelhas.",
      "Empurre acima sem travar cotovelo.",
    ],
    cues: ["Punho neutro ou pronado", "Escápula estável"],
    rating: rate(4.6, 980, "Substitui o militar para quem tem desconforto. Top para hipertrofia."),
    tags: ["compound"],
  },
  {
    id: "lib-arnold-press", name: "Arnold Press", equipment: "dumbbell",
    primary: "shoulders", secondary: ["triceps"], difficulty: 2,
    defaultRestSeconds: 90, defaultTempo: "2-1-2-0",
    shortDescription: "Desenvolvimento com rotação. Ativa anterior + lateral.",
    instructions: [
      "Comece com palmas para o rosto (rosca direta no topo).",
      "Rotacione e empurre acima até palmas para frente.",
      "Reverta a trajetória controlando.",
    ],
    cues: ["Rotação fluida", "Sem balançar"],
    rating: rate(4.4, 620, "Viral pela origem Arnold. Boa variação para deltoides anterior+lateral."),
    tags: ["compound"],
  },
  {
    id: "lib-elevacao-lateral", name: "Elevação Lateral", equipment: "dumbbell",
    primary: "shoulders", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-0-2-1",
    shortDescription: "Isolador rei do deltoide lateral.",
    instructions: [
      "Halteres ao lado, leve flexão de cotovelo (~10°).",
      "Eleve liderando com cotovelo até a altura do ombro.",
      "Desça controlando 2-3s.",
    ],
    cues: ["Mindinho um pouco acima", "Sem balanço de tronco"],
    rating: rate(4.9, 1820, "Provavelmente o isolador mais popular do Gym Tok. Largura de ombro = simetria visual."),
    tags: ["isolation", "beginner-friendly"],
  },
  {
    id: "lib-elevacao-frontal", name: "Elevação Frontal", equipment: "dumbbell",
    primary: "shoulders", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-0-2-0",
    shortDescription: "Foco no deltoide anterior. Geralmente já saturado por supinos.",
    instructions: [
      "Halteres à frente das coxas.",
      "Eleve até a altura do ombro, alternando ou junto.",
    ],
    cues: ["Cotovelo fixo", "Não balançar"],
    rating: rate(3.4, 340, "Subestimado/superestimado. Anterior já recebe muito volume com supino."),
    tags: ["isolation"],
  },
  {
    id: "lib-elevacao-posterior", name: "Crucifixo Inverso (Reverse Fly)", equipment: "dumbbell",
    primary: "shoulders", secondary: ["traps"], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-0-2-1",
    shortDescription: "Foco no deltoide posterior. Ponto fraco da maioria.",
    instructions: [
      "Tronco a 45° ou banco inclinado.",
      "Abra os braços em arco, liderando com cotovelo.",
    ],
    cues: ["Não use trapézio", "Aperte escápulas no topo"],
    rating: rate(4.5, 760, "Cada vez mais pregado no Gym Tok como prioridade para postura/simetria."),
    tags: ["isolation"],
  },
  {
    id: "lib-remada-serrote", name: "Remada Serrote Halter", equipment: "dumbbell",
    primary: "lats", secondary: ["traps", "biceps"], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "2-1-2-0",
    shortDescription: "Unilateral para costas. Maior ROM e mind-muscle.",
    instructions: [
      "Apoie joelho e mão no banco, tronco paralelo ao chão.",
      "Puxe o halter ao quadril, cotovelo colado.",
      "Estenda totalmente embaixo.",
    ],
    cues: ["Não rotacione tronco", "Cotovelo para trás"],
    rating: rate(4.7, 1090, "Top 3 para costas em hipertrofia. Permite focar em cada lado."),
    tags: ["compound", "unilateral"],
  },
  {
    id: "lib-agachamento-goblet", name: "Goblet Squat", equipment: "dumbbell",
    primary: "quads", secondary: ["glutes", "core"], difficulty: 1,
    defaultRestSeconds: 90, defaultTempo: "3-1-1-0",
    shortDescription: "Halter à frente do peito. Iniciante e mobilidade.",
    instructions: [
      "Halter vertical à frente do peito.",
      "Agache mantendo tronco ereto.",
    ],
    cues: ["Cotovelos para baixo", "Profundidade total"],
    rating: rate(4.5, 680, "Excelente para iniciantes e aquecimento. Ensina padrão de agachar."),
    tags: ["compound", "beginner-friendly"],
  },
  {
    id: "lib-bulgaro", name: "Búlgaro (Split Squat)", equipment: "dumbbell",
    primary: "quads", secondary: ["glutes", "hamstrings", "core"], difficulty: 3,
    defaultRestSeconds: 90, defaultTempo: "3-1-1-0",
    shortDescription: "Unilateral. Brutal para perna e estabilidade.",
    instructions: [
      "Pé trás apoiado no banco, frente afastado ~50cm.",
      "Desça vertical, joelho frente sobre o pé.",
      "Suba pela perna da frente.",
    ],
    cues: ["Não force joelho à frente", "Tronco levemente inclinado para glúteo"],
    rating: rate(4.8, 1240, "Hype enorme no Gym Tok feminino. Praticamente substituto do agachamento para muitos."),
    tags: ["compound", "unilateral", "advanced"],
  },
  {
    id: "lib-stiff-halter", name: "Stiff Halter", equipment: "dumbbell",
    primary: "hamstrings", secondary: ["glutes"], difficulty: 2,
    defaultRestSeconds: 90, defaultTempo: "3-1-1-0",
    shortDescription: "Stiff com halteres. Maior controle de ROM.",
    instructions: ["Halteres à frente, hinge posterior, joelhos fixos.", "Desça até alongamento."],
    cues: ["Quadril atrás", "Lombar neutra"],
    rating: rate(4.5, 510, "Boa variação. Recomendada para casa/quem treina sem barra."),
    tags: ["compound"],
  },
  {
    id: "lib-afundo-halter", name: "Afundo Halter", equipment: "dumbbell",
    primary: "quads", secondary: ["glutes", "hamstrings"], difficulty: 2,
    defaultRestSeconds: 90, defaultTempo: "2-1-1-0",
    shortDescription: "Passada alternada. Unilateral + estabilidade.",
    instructions: ["Halteres ao lado.", "Passo à frente, desça até joelho quase tocar o chão."],
    cues: ["Tronco ereto", "Empurre pela frente"],
    rating: rate(4.4, 620, "Versátil. Pode ser estacionário, andando ou reverso."),
    tags: ["compound", "unilateral"],
  },
  {
    id: "lib-rosca-alternada", name: "Rosca Alternada Halter", equipment: "dumbbell",
    primary: "biceps", secondary: ["forearms"], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-0",
    shortDescription: "Bíceps com supinação alternada.",
    instructions: ["Halteres ao lado, palmas para corpo.", "Curl rotacionando até palma para cima."],
    cues: ["Não balance", "Pico de contração"],
    rating: rate(4.3, 720, "Clássico imortal. Rotação ativa bíceps + braquial."),
    tags: ["isolation", "beginner-friendly"],
  },
  {
    id: "lib-rosca-martelo", name: "Rosca Martelo", equipment: "dumbbell",
    primary: "biceps", secondary: ["forearms"], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-0",
    shortDescription: "Pegada neutra. Foco em braquial e braço grosso.",
    instructions: ["Halteres ao lado, palmas voltadas para corpo.", "Curl mantendo a pegada neutra."],
    cues: ["Cotovelo fixo", "Sem balanço"],
    rating: rate(4.6, 980, "Indispensável para braço grosso. Tendência forte no Gym Tok."),
    tags: ["isolation"],
  },
  {
    id: "lib-rosca-concentrada", name: "Rosca Concentrada", equipment: "dumbbell",
    primary: "biceps", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Bíceps isolado, sentado. Pico máximo.",
    instructions: ["Sentado, cotovelo apoiado na coxa interna.", "Curl com mind-muscle máximo."],
    cues: ["Sem ajudar com tronco", "Aperte no topo"],
    rating: rate(4.2, 530, "Cult de bodybuilders. Bom para finishers."),
    tags: ["isolation"],
  },
  {
    id: "lib-rosca-inclinada", name: "Rosca Inclinada Halter", equipment: "dumbbell",
    primary: "biceps", secondary: [], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "3-1-2-0",
    shortDescription: "Banco 60°, braço atrás do tronco. Stretch máximo.",
    instructions: ["Sentado em banco 60°, braços pendurados.", "Curl sem mover cotovelo."],
    cues: ["Ombros para trás", "Stretch embaixo"],
    rating: rate(4.7, 870, "Top tier no Gym Tok científico. Stretch = mais hipertrofia."),
    tags: ["isolation", "stretch"],
  },
  {
    id: "lib-triceps-frances-halter", name: "Tríceps Francês Halter", equipment: "dumbbell",
    primary: "triceps", secondary: [], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "3-1-1-0",
    shortDescription: "Extensão acima da cabeça. Alonga cabeça longa.",
    instructions: ["Halter pegado com duas mãos atrás da cabeça.", "Estenda controlado."],
    cues: ["Cotovelos colados à cabeça", "ROM completo"],
    rating: rate(4.6, 740, "Stretch da cabeça longa = top para tríceps moderno."),
    tags: ["isolation", "stretch"],
  },
  {
    id: "lib-triceps-coice", name: "Tríceps Coice (Kickback)", equipment: "dumbbell",
    primary: "triceps", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Isolador leve. Pico curto.",
    instructions: ["Tronco a 45°, cotovelo paralelo ao tronco.", "Estenda atrás contraindo."],
    cues: ["Cotovelo não move", "Aperta no fim"],
    rating: rate(3.3, 280, "Subótimo: tensão alta só no fim. Use cabos para melhor estímulo."),
    tags: ["isolation"],
  },
  {
    id: "lib-encolhimento-halter", name: "Encolhimento Halter", equipment: "dumbbell",
    primary: "traps", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "1-1-1-1",
    shortDescription: "Trapézio superior com ROM maior que barra.",
    instructions: ["Halteres ao lado.", "Eleve ombros, segure 1s."],
    cues: ["Não rotacione", "Olhar à frente"],
    rating: rate(4.2, 410, "Melhor que barra pela amplitude. Bom finisher para Pull."),
    tags: ["isolation"],
  },
  {
    id: "lib-rdl-halter-unilateral", name: "RDL Unilateral Halter", equipment: "dumbbell",
    primary: "hamstrings", secondary: ["glutes", "core"], difficulty: 3,
    defaultRestSeconds: 75, defaultTempo: "3-1-1-0",
    shortDescription: "RDL em uma perna só. Estabilidade + glúteo médio.",
    instructions: ["Halter na mão oposta à perna apoiada.", "Hinge em pé só, perna livre estende atrás."],
    cues: ["Quadril estável", "Sem rotação"],
    rating: rate(4.5, 460, "Crescendo em popularidade. Excelente para corrigir desequilíbrio."),
    tags: ["compound", "unilateral", "advanced"],
  },
  {
    id: "lib-farmer-walk", name: "Farmer's Walk", equipment: "dumbbell",
    primary: "forearms", secondary: ["traps", "core", "glutes"], difficulty: 2,
    defaultRestSeconds: 90, defaultTempo: "passos",
    shortDescription: "Carregar peso andando. Pegada + core + condicionamento.",
    instructions: ["Halteres/kettlebells pesados em cada mão.", "Caminhe 20-40m mantendo postura."],
    cues: ["Ombros para trás", "Passos curtos"],
    rating: rate(4.7, 890, "Funcional puro. Viraliza pela simplicidade e efeito condicionante."),
    tags: ["compound", "core"],
  },

  /* ════════════════ MÁQUINAS ════════════════ */
  {
    id: "lib-leg-press-45", name: "Leg Press 45°", equipment: "machine", machineName: "Leg Press 45°",
    primary: "quads", secondary: ["glutes", "hamstrings"], difficulty: 2,
    defaultRestSeconds: 150, defaultTempo: "2-1-2-0",
    shortDescription: "Composto para perna sem demanda lombar. Permite cargas altíssimas.",
    instructions: [
      "Pés na plataforma, na largura dos ombros.",
      "Desça até quase encostar coxas no abdômen.",
      "Empurre sem travar joelhos.",
    ],
    cues: ["Lombar colada", "Não trave joelho"],
    rating: rate(4.7, 1340, "Mais seguro que agachamento. Top para hipertrofia."),
    tags: ["compound"],
  },
  {
    id: "lib-hack-squat", name: "Hack Squat", equipment: "machine", machineName: "Hack Squat Machine",
    primary: "quads", secondary: ["glutes"], difficulty: 2,
    defaultRestSeconds: 120, defaultTempo: "3-1-2-0",
    shortDescription: "Padrão guiado de agachamento. Foco brutal em quadríceps.",
    instructions: ["Ombros sob almofadas, pés na plataforma.", "Desça profundo, suba sem travar."],
    cues: ["Pés baixos = mais quad", "Pés altos = mais glúteo"],
    rating: rate(4.8, 1180, "Tendência forte no Gym Tok como 'leg killer'. Quad development top."),
    tags: ["compound"],
  },
  {
    id: "lib-pendulum-squat", name: "Pendulum Squat", equipment: "machine", machineName: "Pendulum Squat",
    primary: "quads", secondary: ["glutes"], difficulty: 2,
    defaultRestSeconds: 120, defaultTempo: "3-1-2-0",
    shortDescription: "Variação curvilínea. Stretch máximo no quad.",
    instructions: ["Ombros nas almofadas, pés na plataforma curva.", "Desça profundo, sinta o quad alongar."],
    cues: ["Profundidade total", "Sem travar"],
    rating: rate(4.7, 540, "Hype recente. Onde tem é fila — efeito visual no quadríceps é nítido."),
    tags: ["compound"],
  },
  {
    id: "lib-cadeira-extensora", name: "Cadeira Extensora", equipment: "machine", machineName: "Leg Extension",
    primary: "quads", secondary: [], difficulty: 1,
    defaultRestSeconds: 75, defaultTempo: "2-1-2-1",
    shortDescription: "Isolador puro de quadríceps. Top para reto femoral.",
    instructions: ["Sentado, tornozelos sob rolo.", "Estenda joelhos até o pico."],
    cues: ["Aperte no topo 1s", "Não solte na descida"],
    rating: rate(4.6, 1010, "Isolador rei do quad. Stretch posicional muito eficaz."),
    tags: ["isolation"],
  },
  {
    id: "lib-cadeira-flexora", name: "Cadeira Flexora Sentada", equipment: "machine", machineName: "Seated Leg Curl",
    primary: "hamstrings", secondary: [], difficulty: 1,
    defaultRestSeconds: 75, defaultTempo: "2-1-3-0",
    shortDescription: "Posterior em posição de stretch. Top moderno.",
    instructions: ["Sentado, rolo sobre tornozelos.", "Flexione joelhos, controle descida."],
    cues: ["Aperte no fim", "Descida 3s"],
    rating: rate(4.7, 980, "Estudos mostram superior à flexora deitada para hipertrofia."),
    tags: ["isolation"],
  },
  {
    id: "lib-mesa-flexora", name: "Mesa Flexora", equipment: "machine", machineName: "Lying Leg Curl",
    primary: "hamstrings", secondary: ["calves"], difficulty: 1,
    defaultRestSeconds: 75, defaultTempo: "2-1-2-1",
    shortDescription: "Posterior deitado. Clássico.",
    instructions: ["Deitado de barriga, rolo sobre tornozelos.", "Flexione joelhos contraindo."],
    cues: ["Quadril colado", "Não impulsione"],
    rating: rate(4.4, 720, "Clássico válido. Mas sentada vence em ranking moderno."),
    tags: ["isolation"],
  },
  {
    id: "lib-adutora", name: "Cadeira Adutora", equipment: "machine", machineName: "Adductor Machine",
    primary: "quads", secondary: ["glutes"], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Isolador para adutores (parte interna da coxa).",
    instructions: ["Sentado, joelhos abertos contra almofadas.", "Aperte para dentro."],
    cues: ["ROM total", "Pico de contração"],
    rating: rate(4.0, 510, "Subestimado: adutor é grande contribuidor para força de agachar."),
    tags: ["isolation"],
  },
  {
    id: "lib-abdutora", name: "Cadeira Abdutora", equipment: "machine", machineName: "Abductor Machine",
    primary: "glutes", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Glúteo médio. Inclinar tronco aumenta ativação.",
    instructions: ["Sentado, joelhos contra almofadas externas.", "Abra contraindo glúteo médio."],
    cues: ["Tronco inclinado à frente", "Sem balanço"],
    rating: rate(4.6, 1140, "Hype Gym Tok feminino. Inclinação faz toda a diferença."),
    tags: ["isolation"],
  },
  {
    id: "lib-mesa-romana", name: "Hiperextensão (Banco Romano 45°)", equipment: "machine", machineName: "45° Hyper Bench",
    primary: "hamstrings", secondary: ["glutes", "lower-back"], difficulty: 1,
    defaultRestSeconds: 75, defaultTempo: "3-1-1-1",
    shortDescription: "Posterior + lombar. Pode focar em glúteo com flexão lombar.",
    instructions: ["Apoiado no banco 45°, hinge para frente.", "Volte sem hiperextender."],
    cues: ["Glúteo: pés rotacionados fora", "Lombar neutra"],
    rating: rate(4.7, 820, "Indispensável para posterior/glúteo. Bombado pelo Bret Contreras."),
    tags: ["compound"],
  },
  {
    id: "lib-glute-ham-raise", name: "Glute Ham Raise (GHR)", equipment: "machine", machineName: "GHR Bench",
    primary: "hamstrings", secondary: ["glutes", "calves"], difficulty: 3,
    defaultRestSeconds: 90, defaultTempo: "3-0-2-0",
    shortDescription: "Posterior em flexão de joelho. Brutalmente difícil.",
    instructions: ["Joelhos no banco, pés travados.", "Desça controlando, suba flexionando joelhos."],
    cues: ["Use assistência se necessário", "Sem usar lombar"],
    rating: rate(4.6, 380, "Hardcore. Top para força funcional do isquiotibial."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-supino-maquina", name: "Supino Máquina (Hammer)", equipment: "machine", machineName: "Plate-Loaded Chest Press",
    primary: "chest", secondary: ["triceps", "shoulders"], difficulty: 1,
    defaultRestSeconds: 90, defaultTempo: "3-1-2-0",
    shortDescription: "Pressão guiada. Útil para drop sets e iniciantes.",
    instructions: ["Banco ajustado para alça na altura do peito.", "Empurre sem travar."],
    cues: ["Escápula retraída", "Sem trancar cotovelo"],
    rating: rate(4.5, 760, "Excelente para finalizar peito. Hammer Strength é gold standard."),
    tags: ["compound", "beginner-friendly"],
  },
  {
    id: "lib-voador-peck-deck", name: "Voador (Peck Deck)", equipment: "machine", machineName: "Pec Deck",
    primary: "chest", secondary: [], difficulty: 1,
    defaultRestSeconds: 75, defaultTempo: "2-1-2-1",
    shortDescription: "Isolador para peitoral. Pico no centro.",
    instructions: ["Sentado, antebraços nas almofadas.", "Junte braços em arco, contraia."],
    cues: ["ROM completo", "Aperte 1s no centro"],
    rating: rate(4.4, 690, "Bom isolador. Crucifixo cabo dá mais ROM, mas peck deck é mais estável."),
    tags: ["isolation"],
  },
  {
    id: "lib-pulldown", name: "Puxada Frontal", equipment: "machine", machineName: "Lat Pulldown",
    primary: "lats", secondary: ["biceps", "traps"], difficulty: 1,
    defaultRestSeconds: 90, defaultTempo: "2-1-2-0",
    shortDescription: "Substituto guiado da barra fixa. Versátil.",
    instructions: ["Pegada pronada larga.", "Puxe a barra ao peito alto contraindo escápulas."],
    cues: ["Não vá para trás", "Cotovelos para baixo"],
    rating: rate(4.7, 1290, "Padrão universal. Top no Gym Tok pela controlabilidade."),
    tags: ["compound", "beginner-friendly"],
  },
  {
    id: "lib-pulldown-supinado", name: "Puxada Supinada", equipment: "machine", machineName: "Lat Pulldown",
    primary: "lats", secondary: ["biceps"], difficulty: 1,
    defaultRestSeconds: 90, defaultTempo: "2-1-2-0",
    shortDescription: "Pegada supinada. Mais bíceps + dorsal inferior.",
    instructions: ["Pegada supinada na largura dos ombros.", "Puxe ao peito baixo."],
    cues: ["Cotovelos para trás", "Tronco estável"],
    rating: rate(4.5, 620, "Variação útil. Combo com pulldown pronado cobre bem dorsais."),
    tags: ["compound"],
  },
  {
    id: "lib-pulldown-neutro", name: "Puxada Neutra", equipment: "machine", machineName: "Lat Pulldown",
    primary: "lats", secondary: ["biceps"], difficulty: 1,
    defaultRestSeconds: 90, defaultTempo: "2-1-2-0",
    shortDescription: "Pega paralela. Confortável e foco em dorsal médio.",
    instructions: ["Pegada paralela com triângulo.", "Puxe ao peito."],
    cues: ["Mind-muscle nos lats", "ROM total"],
    rating: rate(4.6, 540, "Variação confortável. Boa para quem sente desconforto em pronada."),
    tags: ["compound"],
  },
  {
    id: "lib-remada-sentada-maquina", name: "Remada Sentada Máquina", equipment: "machine", machineName: "Seated Cable Row Machine",
    primary: "lats", secondary: ["traps", "biceps"], difficulty: 1,
    defaultRestSeconds: 90, defaultTempo: "2-1-2-0",
    shortDescription: "Remada guiada para densidade de costas.",
    instructions: ["Sentado, peito no apoio.", "Puxe os punhos ao tronco."],
    cues: ["Aperte escápulas", "Sem balanço"],
    rating: rate(4.5, 580, "Confiável. Apoio no peito remove o tronco da equação."),
    tags: ["compound", "beginner-friendly"],
  },
  {
    id: "lib-remada-cavalinho", name: "Remada Cavalinho (T-Bar)", equipment: "machine", machineName: "T-Bar Row",
    primary: "lats", secondary: ["traps", "biceps"], difficulty: 2,
    defaultRestSeconds: 120, defaultTempo: "2-1-2-0",
    shortDescription: "Permite carga pesada com pegada neutra.",
    instructions: ["Em pé sobre a plataforma, tronco inclinado.", "Puxe ao tronco com peito firme."],
    cues: ["Lombar neutra", "Cotovelos próximos"],
    rating: rate(4.6, 720, "Clássico de hipertrofia. Permite muita carga."),
    tags: ["compound"],
  },
  {
    id: "lib-pulldown-unilateral", name: "Puxada Unilateral", equipment: "machine", machineName: "Single-Arm Lat Pulldown",
    primary: "lats", secondary: ["biceps"], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "2-1-2-1",
    shortDescription: "Stretch unilateral máximo. Foco lat puro.",
    instructions: ["Sentado, uma mão na alça D.", "Puxe ao quadril contraindo o lat."],
    cues: ["Stretch total embaixo", "Rotação pélvica leve OK"],
    rating: rate(4.7, 540, "Tendência forte. Eric Helms e Nippard recomendam para hipertrofia avançada."),
    tags: ["isolation", "unilateral", "stretch"],
  },
  {
    id: "lib-desenvolvimento-maquina", name: "Desenvolvimento Máquina", equipment: "machine", machineName: "Shoulder Press Machine",
    primary: "shoulders", secondary: ["triceps"], difficulty: 1,
    defaultRestSeconds: 90, defaultTempo: "2-1-2-0",
    shortDescription: "Pressão de ombro guiada. Drops e iniciantes.",
    instructions: ["Sentado, alças na altura dos ombros.", "Empurre acima."],
    cues: ["Escápula apoiada", "Sem trancar"],
    rating: rate(4.4, 640, "Versão segura do desenvolvimento. Top para finalizar."),
    tags: ["compound", "beginner-friendly"],
  },
  {
    id: "lib-elevacao-lateral-maquina", name: "Elevação Lateral Máquina", equipment: "machine", machineName: "Lateral Raise Machine",
    primary: "shoulders", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-0-3-1",
    shortDescription: "Lateral com resistência constante (vs halter que tem peak na metade).",
    instructions: ["Sentado, cotovelos sob almofadas.", "Eleve até a altura do ombro."],
    cues: ["Não use trapézio", "Descida 3s"],
    rating: rate(4.7, 720, "Game-changer para deltoide lateral. Cresce no Gym Tok."),
    tags: ["isolation"],
  },
  {
    id: "lib-rosca-maquina", name: "Rosca Máquina", equipment: "machine", machineName: "Biceps Curl Machine",
    primary: "biceps", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Curl guiado. Sem balanço possível.",
    instructions: ["Sentado, braços nas almofadas.", "Curl contraindo, segure no topo."],
    cues: ["Cotovelo sempre apoiado", "ROM total"],
    rating: rate(4.3, 480, "Boa para finishers e drop sets. Estável."),
    tags: ["isolation", "beginner-friendly"],
  },
  {
    id: "lib-triceps-maquina", name: "Tríceps Máquina", equipment: "machine", machineName: "Triceps Extension Machine",
    primary: "triceps", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-0",
    shortDescription: "Extensão guiada. Drops fáceis.",
    instructions: ["Sentado, cotovelos apoiados.", "Estenda até quase travar."],
    cues: ["Sem mover ombro", "Pico no final"],
    rating: rate(4.3, 410, "Útil. Cabo solto entrega mais variedade."),
    tags: ["isolation"],
  },
  {
    id: "lib-abdominal-maquina", name: "Abdominal Máquina", equipment: "machine", machineName: "Ab Crunch Machine",
    primary: "core", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Crunch guiado com carga. Hipertrofia abdominal real.",
    instructions: ["Sentado, peito contra almofada.", "Flexione tronco contraindo abs."],
    cues: ["Queixo afastado do peito", "Curva o tronco"],
    rating: rate(4.4, 580, "Carga é o que cresce abs. Subestimado fora do Gym Tok científico."),
    tags: ["isolation", "core"],
  },
  {
    id: "lib-panturrilha-sentada", name: "Panturrilha Sentada", equipment: "machine", machineName: "Seated Calf Raise",
    primary: "calves", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-3-1",
    shortDescription: "Foco no sóleo (porção profunda).",
    instructions: ["Sentado, almofadas sobre joelhos.", "Elevação até pico."],
    cues: ["Stretch máximo embaixo", "Segure 1s no topo"],
    rating: rate(4.5, 620, "Sóleo é responsável por massa lateral da panturrilha. Imprescindível."),
    tags: ["isolation"],
  },
  {
    id: "lib-panturrilha-em-pe", name: "Panturrilha em Pé", equipment: "machine", machineName: "Standing Calf Raise",
    primary: "calves", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-3-1",
    shortDescription: "Foco no gastrocnêmio. ROM total é tudo.",
    instructions: ["Almofadas nos ombros, pés na plataforma.", "Eleve máximo, desça máximo."],
    cues: ["Stretch profundo", "Pico 1s"],
    rating: rate(4.6, 980, "Padrão para panturrilha. ROM completo é regra."),
    tags: ["isolation"],
  },
  {
    id: "lib-smith-squat", name: "Agachamento Smith", equipment: "smith", machineName: "Smith Machine",
    primary: "quads", secondary: ["glutes"], difficulty: 2,
    defaultRestSeconds: 120, defaultTempo: "3-1-2-0",
    shortDescription: "Agachamento guiado vertical. Permite focar no quad.",
    instructions: ["Pés ligeiramente à frente da barra.", "Desça profundo, foco no quad."],
    cues: ["Pés para frente = quad", "Pés sob barra = glúteo"],
    rating: rate(4.4, 580, "Polarizador. Bom para hipertrofia, ruim para padrão de movimento livre."),
    tags: ["compound"],
  },
  {
    id: "lib-smith-bulgaro", name: "Búlgaro Smith", equipment: "smith", machineName: "Smith Machine",
    primary: "quads", secondary: ["glutes"], difficulty: 2,
    defaultRestSeconds: 90, defaultTempo: "3-1-1-0",
    shortDescription: "Búlgaro guiado. Permite focar em estímulo sem cair.",
    instructions: ["Pé trás no banco, barra Smith nos ombros.", "Desça vertical."],
    cues: ["Frente bem afastada", "Tronco ereto"],
    rating: rate(4.6, 720, "Best of both worlds. Tendência forte."),
    tags: ["compound", "unilateral"],
  },

  /* ════════════════ POLIA / CABOS ════════════════ */
  {
    id: "lib-crossover-alto", name: "Crossover Alto", equipment: "cable",
    primary: "chest", secondary: [], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "2-1-2-1",
    shortDescription: "Foco em peito inferior. Movimento descendente.",
    instructions: ["Polias altas, alças nas mãos.", "Junte em arco descendente à frente."],
    cues: ["Tronco levemente inclinado", "Aperte no fim"],
    rating: rate(4.5, 720, "Top para peito inferior + estética. Padrão Gym Tok masculino."),
    tags: ["isolation"],
  },
  {
    id: "lib-crossover-medio", name: "Crossover Médio", equipment: "cable",
    primary: "chest", secondary: [], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "2-1-2-1",
    shortDescription: "Foco no meio do peito. Polias na altura do peito.",
    instructions: ["Polias na altura do peito, alças nas mãos.", "Junte horizontalmente à frente."],
    cues: ["Cotovelos fixos", "Aperte no fim"],
    rating: rate(4.6, 680, "Versão mais 'pec-deck-like'. Tensão constante."),
    tags: ["isolation"],
  },
  {
    id: "lib-crossover-baixo", name: "Crossover Baixo", equipment: "cable",
    primary: "chest", secondary: [], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "2-1-2-1",
    shortDescription: "Foco em peito superior. Movimento ascendente.",
    instructions: ["Polias baixas.", "Junte em arco ascendente."],
    cues: ["Tronco ligeiramente para trás", "Aperte na altura do ombro"],
    rating: rate(4.7, 580, "Excelente para superior do peito. Cresce no Gym Tok científico."),
    tags: ["isolation"],
  },
  {
    id: "lib-pull-around", name: "Cable Pull-Around (Cable Fly)", equipment: "cable",
    primary: "chest", secondary: [], difficulty: 2,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Crucifixo unilateral no cabo. Stretch lateral máximo.",
    instructions: ["Cabo na altura do peito, uma mão.", "Mão começa atrás do corpo, traz para frente em arco."],
    cues: ["Stretch atrás", "Aperta em frente"],
    rating: rate(4.8, 410, "Hype Gym Tok atual. Stretch unilateral entrega massa."),
    tags: ["isolation", "unilateral", "stretch"],
  },
  {
    id: "lib-remada-baixa", name: "Remada Baixa Cabo", equipment: "cable",
    primary: "lats", secondary: ["traps", "biceps"], difficulty: 1,
    defaultRestSeconds: 90, defaultTempo: "2-1-2-0",
    shortDescription: "Remada sentada no cabo. Versátil de pegada.",
    instructions: ["Sentado, pés apoiados.", "Puxe ao abdômen contraindo escápulas."],
    cues: ["Não use tronco", "ROM total"],
    rating: rate(4.6, 920, "Padrão de costas. Triângulo neutro é o setup clássico."),
    tags: ["compound", "beginner-friendly"],
  },
  {
    id: "lib-face-pull", name: "Face Pull", equipment: "cable",
    primary: "shoulders", secondary: ["traps"], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Postura + deltoide posterior. Indispensável.",
    instructions: ["Polia alta, corda.", "Puxe à altura do rosto, cotovelos abertos."],
    cues: ["Cotovelos altos", "Rotação externa no fim"],
    rating: rate(4.8, 1140, "Universalmente recomendado. Saúde do ombro + estética."),
    tags: ["isolation"],
  },
  {
    id: "lib-pull-through", name: "Pull-Through Cabo", equipment: "cable",
    primary: "glutes", secondary: ["hamstrings"], difficulty: 1,
    defaultRestSeconds: 75, defaultTempo: "2-1-2-1",
    shortDescription: "Hinge no cabo. Glúteo + posterior sem carga lombar.",
    instructions: ["De costas para polia baixa, corda entre as pernas.", "Hinge para trás, depois extensão de quadril."],
    cues: ["Quadril atrás", "Sem usar braços"],
    rating: rate(4.6, 480, "Ótima alternativa ao stiff. Foco em glúteo."),
    tags: ["compound"],
  },
  {
    id: "lib-cable-row-unilateral", name: "Remada Cabo Unilateral", equipment: "cable",
    primary: "lats", secondary: ["biceps"], difficulty: 2,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Remada com uma mão. ROM e rotação adicionais.",
    instructions: ["Sentado ou em pé, uma mão na alça.", "Puxe ao tronco rotacionando levemente."],
    cues: ["Stretch máximo", "Cotovelo para trás"],
    rating: rate(4.5, 410, "Variação versátil. Bom para finalizar costas."),
    tags: ["compound", "unilateral"],
  },
  {
    id: "lib-triceps-corda", name: "Tríceps Corda Polia", equipment: "cable",
    primary: "triceps", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-0",
    shortDescription: "Extensão com corda. Abre no fim para mais pico.",
    instructions: ["Polia alta, corda.", "Cotovelos pinados, empurre para baixo abrindo no fim."],
    cues: ["Cotovelos colados", "Abre no final"],
    rating: rate(4.5, 980, "Padrão universal. Bombado pela versatilidade."),
    tags: ["isolation", "beginner-friendly"],
  },
  {
    id: "lib-triceps-barra-polia", name: "Tríceps Barra Polia", equipment: "cable",
    primary: "triceps", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-0",
    shortDescription: "Extensão com barra V ou reta no cabo.",
    instructions: ["Polia alta, barra.", "Cotovelos colados, estenda."],
    cues: ["Sem balanço", "ROM completo"],
    rating: rate(4.4, 720, "Estável. Boa carga pesada."),
    tags: ["isolation"],
  },
  {
    id: "lib-triceps-unilateral-polia", name: "Tríceps Unilateral Polia", equipment: "cable",
    primary: "triceps", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Tríceps cabo com uma mão. Foco em cada lado.",
    instructions: ["Alça D, pegada supinada ou pronada.", "Estenda controlado."],
    cues: ["Mind-muscle", "Cotovelo fixo"],
    rating: rate(4.5, 480, "Excelente para corrigir desequilíbrio. Bom finisher."),
    tags: ["isolation", "unilateral"],
  },
  {
    id: "lib-triceps-overhead-corda", name: "Tríceps Francês Corda Polia", equipment: "cable",
    primary: "triceps", secondary: [], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "3-1-2-0",
    shortDescription: "Extensão acima da cabeça no cabo. Stretch cabeça longa.",
    instructions: ["Polia baixa, corda atrás da cabeça.", "Estenda acima."],
    cues: ["Cotovelos colados à cabeça", "Stretch máximo"],
    rating: rate(4.8, 620, "Top moderno. Stretch é o que cresce o tríceps."),
    tags: ["isolation", "stretch"],
  },
  {
    id: "lib-rosca-polia", name: "Rosca Polia", equipment: "cable",
    primary: "biceps", secondary: ["forearms"], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Curl com cabo. Tensão constante.",
    instructions: ["Polia baixa, barra ou corda.", "Curl mantendo cotovelos colados."],
    cues: ["Sem balanço", "Aperte no topo"],
    rating: rate(4.6, 720, "Tensão constante = mais hipertrofia. Tendência forte."),
    tags: ["isolation"],
  },
  {
    id: "lib-rosca-bayesian", name: "Rosca Bayesiana Cabo", equipment: "cable",
    primary: "biceps", secondary: [], difficulty: 2,
    defaultRestSeconds: 60, defaultTempo: "3-1-2-1",
    shortDescription: "Curl unilateral com braço atrás do corpo. Stretch máximo.",
    instructions: ["Cabo na polia baixa atrás de você, alça D.", "Curl com cotovelo atrás do tronco."],
    cues: ["Não mexa o cotovelo", "Stretch é o ponto"],
    rating: rate(4.9, 540, "Bayesian boy. Viraliza no Gym Tok pelo apelo científico do stretch."),
    tags: ["isolation", "unilateral", "stretch"],
  },
  {
    id: "lib-elevacao-lateral-cabo", name: "Elevação Lateral Cabo", equipment: "cable",
    primary: "shoulders", secondary: [], difficulty: 2,
    defaultRestSeconds: 60, defaultTempo: "2-0-3-1",
    shortDescription: "Lateral com tensão constante. Stretch embaixo.",
    instructions: ["Polia baixa atrás das pernas, alça D.", "Eleve até altura do ombro."],
    cues: ["Cabo cruza o corpo embaixo", "Sem trapézio"],
    rating: rate(4.8, 690, "Considerado o melhor para lateral por muitos coaches modernos."),
    tags: ["isolation", "unilateral"],
  },
  {
    id: "lib-reverse-fly-cabo", name: "Crucifixo Inverso Cabo (Cross)", equipment: "cable",
    primary: "shoulders", secondary: [], difficulty: 2,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Posterior do deltoide. Cabos cruzados.",
    instructions: ["Polias altas, cabos cruzados.", "Abra os braços horizontalmente."],
    cues: ["Cotovelos altos", "Aperte escápula"],
    rating: rate(4.7, 510, "Top para posterior. Tensão constante."),
    tags: ["isolation"],
  },
  {
    id: "lib-abducao-cabo", name: "Abdução Glúteo Cabo (Kickback)", equipment: "cable",
    primary: "glutes", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Kickback de glúteo no cabo. Top para glúteo médio/máximo.",
    instructions: ["Tornozeleira, polia baixa.", "Chute para trás contraindo glúteo."],
    cues: ["Sem usar lombar", "Pico no fim"],
    rating: rate(4.7, 1180, "Padrão Gym Tok feminino. Glúteo desenvolvimento direto."),
    tags: ["isolation", "unilateral"],
  },
  {
    id: "lib-abducao-quadril-cabo", name: "Abdução Quadril Cabo", equipment: "cable",
    primary: "glutes", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Glúteo médio lateral. Cabo na perna externa.",
    instructions: ["Tornozeleira, perna externa ao cabo.", "Eleve lateralmente."],
    cues: ["Tronco estável", "Pico segurando"],
    rating: rate(4.6, 720, "Cresce glúteo médio rápido. Padrão feminino."),
    tags: ["isolation", "unilateral"],
  },
  {
    id: "lib-pulldown-straight-arm", name: "Pulldown Braço Reto", equipment: "cable",
    primary: "lats", secondary: ["core"], difficulty: 2,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Isolador puro de lats. Sem bíceps.",
    instructions: ["Polia alta, barra.", "Braços retos, puxe ao quadril."],
    cues: ["Sem flexão de cotovelo", "Aperte os lats"],
    rating: rate(4.6, 580, "Excelente isolador. Cresce no Gym Tok científico."),
    tags: ["isolation"],
  },
  {
    id: "lib-woodchopper", name: "Woodchopper Cabo", equipment: "cable",
    primary: "obliques", secondary: ["core"], difficulty: 2,
    defaultRestSeconds: 60, defaultTempo: "2-0-2-0",
    shortDescription: "Rotação diagonal. Funcional para core.",
    instructions: ["Polia alta, corpo lateral.", "Puxe diagonal de cima para baixo, rotacionando."],
    cues: ["Quadril gira", "Braços retos"],
    rating: rate(4.3, 410, "Bom acessório funcional. Oblíquos sentem."),
    tags: ["core"],
  },
  {
    id: "lib-cable-crunch", name: "Abdominal Cabo Ajoelhado", equipment: "cable",
    primary: "core", secondary: [], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "2-1-2-1",
    shortDescription: "Crunch com carga. Top para abs hipertrofia.",
    instructions: ["Ajoelhado, corda atrás da nuca.", "Flexione tronco contraindo abdômen."],
    cues: ["Quadril fixo", "Curve a coluna"],
    rating: rate(4.7, 870, "Top para abs com carga. Indispensável."),
    tags: ["isolation", "core"],
  },

  /* ════════════════ PESO CORPORAL / CALISTENIA ════════════════ */
  {
    id: "lib-barra-fixa-pronada", name: "Barra Fixa Pronada", equipment: "bodyweight",
    primary: "lats", secondary: ["biceps", "traps"], difficulty: 3,
    defaultRestSeconds: 120, defaultTempo: "2-0-3-1",
    shortDescription: "Padrão-ouro para dorsais. Difícil = recompensador.",
    instructions: ["Pegada pronada largura pouco maior que ombros.", "Puxe o peito à barra."],
    cues: ["Escápulas ativas embaixo", "Descida controlada"],
    rating: rate(4.9, 1640, "Quase unanimidade: top exercício de costas. Métrica de força do Gym Tok."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-barra-fixa-supinada", name: "Barra Fixa Supinada (Chin-up)", equipment: "bodyweight",
    primary: "biceps", secondary: ["lats"], difficulty: 3,
    defaultRestSeconds: 120, defaultTempo: "2-0-3-1",
    shortDescription: "Pega supinada. Mais bíceps, menos lat.",
    instructions: ["Pegada supinada na largura dos ombros.", "Puxe o queixo acima da barra."],
    cues: ["Cotovelos para frente", "ROM completo"],
    rating: rate(4.7, 1180, "Top para bíceps + dorsal. Mais bíceps que pronada."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-barra-fixa-neutra", name: "Barra Fixa Neutra", equipment: "bodyweight",
    primary: "lats", secondary: ["biceps"], difficulty: 3,
    defaultRestSeconds: 120, defaultTempo: "2-0-3-1",
    shortDescription: "Pega paralela. Confortável e potente.",
    instructions: ["Pegada paralela.", "Puxe peito à barra."],
    cues: ["Pega firme", "ROM completo"],
    rating: rate(4.7, 920, "Variante mais confortável. Stretch melhor."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-paralela-mergulho", name: "Paralelas (Dips)", equipment: "bodyweight",
    primary: "chest", secondary: ["triceps", "shoulders"], difficulty: 3,
    defaultRestSeconds: 120, defaultTempo: "3-1-1-0",
    shortDescription: "Peso corporal. Foco no peito (inclinado) ou tríceps (vertical).",
    instructions: ["Suspenso nas paralelas, leve inclinação à frente para peito.", "Desça até cotovelos a 90°."],
    cues: ["Sem fechar ombro demais", "Peito alto"],
    rating: rate(4.8, 1280, "Composto top para peito inferior + tríceps. Gym Tok adora."),
    tags: ["compound", "advanced"],
  },
  {
    id: "lib-flexao-normal", name: "Flexão de Braço (Push-Up)", equipment: "bodyweight",
    primary: "chest", secondary: ["triceps", "shoulders", "core"], difficulty: 1,
    defaultRestSeconds: 60, defaultTempo: "3-1-1-0",
    shortDescription: "Clássico. Versátil, sem equipamento.",
    instructions: ["Mãos na largura dos ombros.", "Desça até peito tocar o chão, suba."],
    cues: ["Core travado", "Cotovelos ~45°"],
    rating: rate(4.5, 1090, "Subestimado. Pode ser progressivo (decline, weighted, plyo)."),
    tags: ["compound", "beginner-friendly"],
  },
  {
    id: "lib-flexao-diamante", name: "Flexão Diamante", equipment: "bodyweight",
    primary: "triceps", secondary: ["chest"], difficulty: 2,
    defaultRestSeconds: 60, defaultTempo: "3-1-1-0",
    shortDescription: "Mãos juntas formando diamante. Tríceps puro.",
    instructions: ["Polegares e indicadores se tocam.", "Desça até peito tocar as mãos."],
    cues: ["Cotovelos colados", "ROM completo"],
    rating: rate(4.4, 540, "Top para tríceps sem equipamento."),
    tags: ["compound"],
  },
  {
    id: "lib-flexao-declinada", name: "Flexão Declinada", equipment: "bodyweight",
    primary: "chest", secondary: ["shoulders"], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "3-1-1-0",
    shortDescription: "Pés elevados. Foco em peito superior.",
    instructions: ["Pés em banco ou caixa.", "Desça profundo."],
    cues: ["Sem cair o quadril", "Cotovelos 45°"],
    rating: rate(4.4, 420, "Progressão natural da flexão. Boa para superior."),
    tags: ["compound"],
  },
  {
    id: "lib-pistol-squat", name: "Pistol Squat", equipment: "bodyweight",
    primary: "quads", secondary: ["glutes", "core"], difficulty: 3,
    defaultRestSeconds: 90, defaultTempo: "3-1-1-0",
    shortDescription: "Agachamento unilateral profundo. Brutal.",
    instructions: ["Apoie em uma perna, a outra estendida à frente.", "Desça profundo, suba."],
    cues: ["Use apoio se necessário", "Equilíbrio é tudo"],
    rating: rate(4.5, 380, "Challenge popular. Excelente para força funcional."),
    tags: ["compound", "unilateral", "advanced"],
  },
  {
    id: "lib-muscle-up", name: "Muscle-Up", equipment: "bodyweight",
    primary: "lats", secondary: ["chest", "triceps", "biceps"], difficulty: 3,
    defaultRestSeconds: 180, defaultTempo: "explosivo",
    shortDescription: "Barra fixa + transição para dip. Avançadíssimo.",
    instructions: ["Pull-up explosivo + rotação para passar sobre a barra.", "Estenda em dip."],
    cues: ["Use kipping para aprender", "Pegada firme"],
    rating: rate(4.6, 480, "Goal de calistenia. Viraliza no Gym Tok como flex."),
    tags: ["compound", "explosive", "advanced"],
  },
  {
    id: "lib-prancha", name: "Prancha (Plank)", equipment: "bodyweight",
    primary: "core", secondary: ["obliques", "shoulders"], difficulty: 1,
    defaultRestSeconds: 45, defaultTempo: "isométrico",
    shortDescription: "Isométrico de core. Versátil.",
    instructions: ["Apoie antebraços e dedos do pé.", "Mantenha linha corpo reta."],
    cues: ["Glúteo apertado", "Sem cair quadril"],
    rating: rate(4.0, 720, "Bom para estabilidade. Não é o melhor para hipertrofia abdominal."),
    tags: ["isolation", "core", "beginner-friendly"],
  },
  {
    id: "lib-prancha-lateral", name: "Prancha Lateral", equipment: "bodyweight",
    primary: "obliques", secondary: ["core"], difficulty: 2,
    defaultRestSeconds: 45, defaultTempo: "isométrico",
    shortDescription: "Foco em oblíquos. Lateral.",
    instructions: ["Apoie antebraço lateral, corpo alinhado.", "Mantenha quadril alto."],
    cues: ["Glúteo apertado", "Linha reta"],
    rating: rate(4.2, 410, "Top para oblíquos. Versátil."),
    tags: ["isolation", "core"],
  },
  {
    id: "lib-hanging-leg-raise", name: "Elevação de Pernas na Barra", equipment: "bodyweight",
    primary: "core", secondary: ["obliques"], difficulty: 3,
    defaultRestSeconds: 75, defaultTempo: "2-1-3-0",
    shortDescription: "Pernas estendidas elevadas. Top abdominal.",
    instructions: ["Pendurado na barra.", "Eleve pernas estendidas até 90° ou mais."],
    cues: ["Sem balançar", "Controle na descida"],
    rating: rate(4.7, 620, "Premium para abs. Stretch + carga corporal."),
    tags: ["isolation", "core", "advanced"],
  },
  {
    id: "lib-mountain-climber", name: "Mountain Climber", equipment: "bodyweight",
    primary: "core", secondary: ["shoulders", "quads"], difficulty: 1,
    defaultRestSeconds: 45, defaultTempo: "explosivo",
    shortDescription: "Cardio + core dinâmico.",
    instructions: ["Posição de prancha alta.", "Alterne joelhos ao peito rapidamente."],
    cues: ["Quadril estável", "Ritmo constante"],
    rating: rate(3.9, 540, "Bom warm-up/cardio. Não substitui abs com carga."),
    tags: ["core", "explosive"],
  },
  {
    id: "lib-burpee", name: "Burpee", equipment: "bodyweight",
    primary: "quads", secondary: ["chest", "core", "shoulders"], difficulty: 2,
    defaultRestSeconds: 60, defaultTempo: "explosivo",
    shortDescription: "Full-body explosivo. Condicionamento.",
    instructions: ["Agachamento + prancha + flexão + salto.", "Encadear sem pausa."],
    cues: ["Ritmo constante", "Aterrissagem leve"],
    rating: rate(4.0, 720, "Condicionamento brutal. Polarizador."),
    tags: ["compound", "explosive"],
  },

  /* ════════════════ KETTLEBELL / FUNCIONAL ════════════════ */
  {
    id: "lib-kb-swing", name: "Kettlebell Swing", equipment: "kettlebell",
    primary: "glutes", secondary: ["hamstrings", "core", "shoulders"], difficulty: 2,
    defaultRestSeconds: 75, defaultTempo: "explosivo",
    shortDescription: "Hinge explosivo. Posterior + cardio.",
    instructions: ["Pés afastados, kettlebell entre as pernas.", "Empurre quadril à frente, kettlebell sobe por inércia."],
    cues: ["Power vem do quadril", "Braços relaxados"],
    rating: rate(4.7, 820, "Tendência forte. Pavel Tsatsouline gospel."),
    tags: ["compound", "explosive"],
  },
  {
    id: "lib-kb-goblet", name: "Goblet Squat Kettlebell", equipment: "kettlebell",
    primary: "quads", secondary: ["glutes", "core"], difficulty: 1,
    defaultRestSeconds: 75, defaultTempo: "3-1-1-0",
    shortDescription: "Agachamento com kb no peito. Funcional.",
    instructions: ["Kettlebell vertical à frente do peito.", "Agache profundo."],
    cues: ["Cotovelos para baixo", "Profundidade total"],
    rating: rate(4.6, 480, "Excelente para iniciantes e aquecimento."),
    tags: ["compound", "beginner-friendly"],
  },
  {
    id: "lib-kb-clean-jerk", name: "Kettlebell Clean & Jerk", equipment: "kettlebell",
    primary: "shoulders", secondary: ["quads", "core", "glutes"], difficulty: 3,
    defaultRestSeconds: 120, defaultTempo: "explosivo",
    shortDescription: "Olímpico unilateral com kettlebell.",
    instructions: ["Clean: kb do chão ao rack frontal.", "Jerk: pequeno dip + empurra acima."],
    cues: ["Movimento fluido", "Sem pausa entre fases"],
    rating: rate(4.3, 320, "Funcional avançado. Requer técnica."),
    tags: ["compound", "explosive", "advanced"],
  },
  {
    id: "lib-kb-snatch", name: "Kettlebell Snatch", equipment: "kettlebell",
    primary: "shoulders", secondary: ["glutes", "core", "lats"], difficulty: 3,
    defaultRestSeconds: 90, defaultTempo: "explosivo",
    shortDescription: "Do chão ao topo em uma mão. Brutal.",
    instructions: ["Swing alto + puxa direto acima da cabeça.", "Aterrissa sem balançar."],
    cues: ["Pega firme", "Pulse no quadril"],
    rating: rate(4.5, 380, "Funcional top. Cardio + força."),
    tags: ["compound", "explosive", "advanced"],
  },
  {
    id: "lib-turkish-getup", name: "Turkish Get-Up", equipment: "kettlebell",
    primary: "core", secondary: ["shoulders", "glutes", "quads"], difficulty: 3,
    defaultRestSeconds: 90, defaultTempo: "controlado",
    shortDescription: "Levantar-se do chão com kb acima da cabeça. Estabilidade total.",
    instructions: ["Deitado, kb estendido acima.", "Levante para de pé sem perder o kb acima."],
    cues: ["Olhe para o kb", "Movimento lento"],
    rating: rate(4.5, 410, "Cult Strongfirst. Excelente para estabilidade global."),
    tags: ["compound", "core", "advanced"],
  },

  /* ════════════════ CARDIO ════════════════ */
  {
    id: "lib-esteira-hiit", name: "Esteira HIIT", equipment: "cardio", machineName: "Esteira",
    primary: "quads", secondary: ["calves", "core"], difficulty: 2,
    defaultRestSeconds: 60, defaultTempo: "intervalos",
    shortDescription: "Sprints 30s + caminhada 60s. Cardio brutal.",
    instructions: ["10x: 30s sprint + 60s caminhada.", "Aquecimento e desaquecimento 5min."],
    cues: ["Não segure corrimão durante sprint", "Inclinação 1-2%"],
    rating: rate(4.5, 620, "Top para condicionamento. Compatível com hipertrofia se moderado."),
    tags: ["explosive"],
  },
  {
    id: "lib-air-bike", name: "Air Bike (Assault Bike)", equipment: "cardio", machineName: "Air Bike",
    primary: "quads", secondary: ["chest", "lats", "core"], difficulty: 2,
    defaultRestSeconds: 60, defaultTempo: "intervalos",
    shortDescription: "Bicicleta com resistência por ar + braços. Brutal.",
    instructions: ["Pedale e empurre/puxe alças.", "Intervalos 30s on / 30s off."],
    cues: ["Postura ereta", "Ritmo constante"],
    rating: rate(4.7, 510, "Padrão CrossFit. Cardio + condicionamento total."),
    tags: ["compound", "explosive"],
  },
  {
    id: "lib-rowing", name: "Remo Ergômetro", equipment: "cardio", machineName: "Rower",
    primary: "lats", secondary: ["lower-back", "quads", "biceps"], difficulty: 2,
    defaultRestSeconds: 90, defaultTempo: "ritmado",
    shortDescription: "Cardio + costas + pernas. Low impact.",
    instructions: ["Empurre com pernas, puxe com braços, role tronco.", "Sequência: pernas → costas → braços."],
    cues: ["Não puxe só com braço", "Ritmo controlado"],
    rating: rate(4.6, 580, "Low-impact. Excelente cardio sem afetar perna."),
    tags: ["compound"],
  },
  {
    id: "lib-sled-push", name: "Sled Push", equipment: "cardio", machineName: "Sled",
    primary: "quads", secondary: ["glutes", "calves", "core"], difficulty: 2,
    defaultRestSeconds: 90, defaultTempo: "explosivo",
    shortDescription: "Empurrar trenó. Perna + cardio + sem excentrico.",
    instructions: ["Carregue o trenó, empurre baixo com tronco inclinado.", "20-40m por série."],
    cues: ["Passos curtos potentes", "Empurre forte"],
    rating: rate(4.8, 420, "Hype atual. Zero soreness, máximo condicionamento."),
    tags: ["compound", "explosive"],
  },
  {
    id: "lib-jump-rope", name: "Pular Corda", equipment: "cardio", machineName: "Corda",
    primary: "calves", secondary: ["core", "shoulders"], difficulty: 1,
    defaultRestSeconds: 45, defaultTempo: "explosivo",
    shortDescription: "Cardio + panturrilha + coordenação.",
    instructions: ["Pulos curtos, punhos rotacionam.", "3min on / 1min off."],
    cues: ["Apoie ponta dos pés", "Cotovelos colados"],
    rating: rate(4.4, 480, "Excelente warm-up. Coordenação e cardio."),
    tags: ["explosive"],
  },
  {
    id: "lib-box-jump", name: "Box Jump", equipment: "cardio", machineName: "Caixa Pliométrica",
    primary: "quads", secondary: ["glutes", "calves"], difficulty: 2,
    defaultRestSeconds: 90, defaultTempo: "explosivo",
    shortDescription: "Salto explosivo sobre caixa. Potência.",
    instructions: ["Posicione-se à frente da caixa.", "Salte e aterrisse macio em cima."],
    cues: ["Desça (não pule de volta)", "Joelhos absorvem"],
    rating: rate(4.5, 410, "Top para potência. Risco de canela se mal executado."),
    tags: ["explosive"],
  },
];

export const EQUIPMENT_LABEL: Record<Equipment, string> = {
  barbell: "Barra Livre",
  dumbbell: "Halter",
  cable: "Polia",
  machine: "Máquina",
  bodyweight: "Peso Corporal",
  kettlebell: "Kettlebell",
  smith: "Smith",
  cardio: "Cardio",
};

export const MUSCLE_LABEL: Record<MuscleId, string> = {
  chest: "Peito",
  shoulders: "Ombros",
  biceps: "Bíceps",
  triceps: "Tríceps",
  forearms: "Antebraço",
  core: "Core",
  obliques: "Oblíquos",
  quads: "Quadríceps",
  hamstrings: "Posterior",
  glutes: "Glúteos",
  calves: "Panturrilha",
  lats: "Latíssimo",
  traps: "Trapézio",
  "lower-back": "Lombar",
  neck: "Pescoço",
};

export const TAG_LABEL: Record<ExerciseTag, string> = {
  compound: "Composto",
  isolation: "Isolador",
  unilateral: "Unilateral",
  explosive: "Explosivo",
  core: "Core",
  stretch: "Stretch",
  "beginner-friendly": "Iniciante",
  advanced: "Avançado",
};

export function getLibraryExercise(id: string): LibraryExercise | undefined {
  return EXERCISE_LIBRARY.find((e) => e.id === id);
}

/** Filtra exercícios cuja primária OU secundárias inclui o músculo dado. */
export function findAlternativesByMuscle(muscle: MuscleId, excludeId?: string): LibraryExercise[] {
  return EXERCISE_LIBRARY
    .filter((e) => e.id !== excludeId && (e.primary === muscle || e.secondary.includes(muscle)))
    .sort((a, b) => b.rating.stars - a.rating.stars || b.rating.sampleSize - a.rating.sampleSize);
}
