/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWorkoutRouteImport } from './routes/_app.workout'
import { Route as AppTerminalRouteImport } from './routes/_app.terminal'
import { Route as AppOperatorRouteImport } from './routes/_app.operator'
import { Route as AppLogisticsRouteImport } from './routes/_app.logistics'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppIntelRouteImport } from './routes/_app.intel'
import { Route as AppBuilderRouteImport } from './routes/_app.builder'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutRoute = AppWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalRoute = AppTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorRoute = AppOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelRoute = AppIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => AppRoute,
} as any)
const AppBuilderRoute = AppBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/builder': typeof AppBuilderRoute
  '/intel': typeof AppIntelRoute
  '/library': typeof AppLibraryRoute
  '/logistics': typeof AppLogisticsRoute
  '/operator': typeof AppOperatorRoute
  '/terminal': typeof AppTerminalRoute
  '/workout': typeof AppWorkoutRoute
}
export interface FileRoutesByTo {
  '/builder': typeof AppBuilderRoute
  '/intel': typeof AppIntelRoute
  '/library': typeof AppLibraryRoute
  '/logistics': typeof AppLogisticsRoute
  '/operator': typeof AppOperatorRoute
  '/terminal': typeof AppTerminalRoute
  '/workout': typeof AppWorkoutRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/builder': typeof AppBuilderRoute
  '/_app/intel': typeof AppIntelRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/logistics': typeof AppLogisticsRoute
  '/_app/operator': typeof AppOperatorRoute
  '/_app/terminal': typeof AppTerminalRoute
  '/_app/workout': typeof AppWorkoutRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/intel'
    | '/library'
    | '/logistics'
    | '/operator'
    | '/terminal'
    | '/workout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/builder'
    | '/intel'
    | '/library'
    | '/logistics'
    | '/operator'
    | '/terminal'
    | '/workout'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/builder'
    | '/_app/intel'
    | '/_app/library'
    | '/_app/logistics'
    | '/_app/operator'
    | '/_app/terminal'
    | '/_app/workout'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workout': {
      id: '/_app/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AppWorkoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terminal': {
      id: '/_app/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AppTerminalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operator': {
      id: '/_app/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AppOperatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logistics': {
      id: '/_app/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intel': {
      id: '/_app/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof AppIntelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builder': {
      id: '/_app/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AppBuilderRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuilderRoute: typeof AppBuilderRoute
  AppIntelRoute: typeof AppIntelRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppOperatorRoute: typeof AppOperatorRoute
  AppTerminalRoute: typeof AppTerminalRoute
  AppWorkoutRoute: typeof AppWorkoutRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuilderRoute: AppBuilderRoute,
  AppIntelRoute: AppIntelRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppOperatorRoute: AppOperatorRoute,
  AppTerminalRoute: AppTerminalRoute,
  AppWorkoutRoute: AppWorkoutRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
