/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWorkoutRouteImport } from './routes/_app.workout'
import { Route as AppLogisticsRouteImport } from './routes/_app.logistics'
import { Route as AppBuilderRouteImport } from './routes/_app.builder'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutRoute = AppWorkoutRouteImport.update({
  id: '/_app/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/_app/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBuilderRoute = AppBuilderRouteImport.update({
  id: '/_app/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/builder': typeof AppBuilderRoute
  '/logistics': typeof AppLogisticsRoute
  '/workout': typeof AppWorkoutRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/builder': typeof AppBuilderRoute
  '/logistics': typeof AppLogisticsRoute
  '/workout': typeof AppWorkoutRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/builder': typeof AppBuilderRoute
  '/_app/logistics': typeof AppLogisticsRoute
  '/_app/workout': typeof AppWorkoutRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/builder' | '/logistics' | '/workout' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/builder' | '/logistics' | '/workout' | '/'
  id:
    | '__root__'
    | '/_app/builder'
    | '/_app/logistics'
    | '/_app/workout'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppBuilderRoute: typeof AppBuilderRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppWorkoutRoute: typeof AppWorkoutRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workout': {
      id: '/_app/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AppWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/logistics': {
      id: '/_app/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/builder': {
      id: '/_app/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AppBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppBuilderRoute: AppBuilderRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppWorkoutRoute: AppWorkoutRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
